%YAML:1.0
---
calibration_time: "2020年12月10日 星期四 00时56分13秒"
image_width: 1280
image_height: 720
flags: 0
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 369.502083, 0., 640, 0.,
       369.502083, 360, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 0., 0.,
       0., 0.,
       0. ]
avg_reprojection_error: 3.6230357516243089e-01